### ISSUE TITLE
Sakura CLIをインストール・アップデートするためのshell scriptを配布する

### ISSUE THREAD

**Issue by sizumita** [machikado-network/machikado.network#6]

**Comment by miminashi** [comment]
インストールのほうはこんな感じか？
https://github.com/sizumita/machikado.network/blob/setup_script/tinc_node/setup_node_with_sakura.sh

sakuraが対応してるどのアーキテクチャでもこんな感じのワンライナーでセットアップできるようになる
```sh
url="https://bit.ly/3BQ5XJr";(curl -L "${url}" || wget -O - "${url}") > /tmp/s; sudo sh /tmp/s <ノード名> <IPアドレス>
```

**Comment by sizumita** [comment]
curl wget対応、マルチアーキテクチャ対応終わりました
